[project]
name = "kanban-mcp-server"
version = "0.1.0"
description = "FastMCP server for kanban task management"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.3.4",
    "requests>=2.32.3",
]
