feature-request:
  description: AI-powered feature request management for Linear
  enabled: true
  url: http://nova-feature-request:8000/mcp/
google-workspace:
  description: Google Workspace MCP Server for Gmail and Calendar operations
  enabled: true
  url: http://nova-google-workspace:8000/mcp/